<?php

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $escaper \Magento\Framework\Escaper */
$json = $block->getViewModel();
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()):?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()):?>
                <div class="field qty">
                    <div id="qty-container" class="qty-container" data-bind="scope: 'qty-counter'">
                    <!--ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "#qty-container": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "qty-counter": {
                                                "component": "qty-counter",
                                                "config": {
                                                    "qty": <?= (int)$block->getProductDefaultQty(); ?>,
                                                    "title": "Quantity",
                                                    "dataValidate": <?= $json->serialize($block->getQuantityValidators()); ?>,
                                                    "decreaseImage": <?= $json->serialize($block->getViewFileUrl('Magento_Catalog::images/minus-sign.svg')); ?>,
                                                    "increaseImage": <?= $json->serialize($block->getViewFileUrl('Magento_Catalog::images/plus-sign.svg')); ?>
                                                }
                                            }
                                         }
                                    }
                                }
                            }
                        </script>
                    </div>
                    <?php if ($block->displayProductStockStatus()):?>
                        <?php if ($_product->isAvailable()):?>
                            <div class="stock-amount-container" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                                <div class="stock available">
                                    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/check-mark.svg')?>" alt="check-mark">
                                    <?= $escaper->escapeHtml(__('In stock')) ?>
                                </div>
                                <div>
                                    <?= $_product->getData("quantity_and_stock_status/qty"); ?> items available
                                </div>
                            </div>

                        <?php else:?>
                            <div class="stock unavailable" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                                <?= $escaper->escapeHtml(__('Out of stock')) ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
