<?php

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()):?>
    <div class="additional-attributes-wrapper">
        <ul class="attributes-list">
            <?php foreach ($_additional as $_data):?>
                <li>
                    <strong class="col label"><?= $escaper->escapeHtml($_data['label']) ?>:</strong>
                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif;?>
