<?php
/** @var \Magebit\PageListWidget\Block\Widget\PageList $block */
/** @var \Magento\Framework\Escaper $escaper */
$selectedPages = $block->getSelectedPages();
?>
<div>
  <nav>
    <h3><?= $escaper->escapeHtml($block->getData("title")) ?></h3>
    <ul>
      <?php foreach ($selectedPages as $page): ?>
      <li><a href="/<?= $escaper->escapeHtml($page['value']) ?>"><?= $escaper->escapeHtml($page['label']) ?></a></li>
      <?php endforeach; ?>
    </ul>
  </nav>
</div>
