<?php
/** @var \Magebit\Faq\Block\Faq $block */
/** @var \Magento\Framework\Escaper $escaper */
$activeFaqs = $block->getFaqsByStatus();
?>
<?php if (isset($activeFaqs[0])): ?>
    <div class="faq-container">
        <h3 class="faq-title">Frequently Asked Questions</h3>
        <?php foreach ($activeFaqs as $faq): ?>
            <div class="faq-item">
                <div class="faq-question-container" data-role="collapsible">
                    <h4 class="faq-question">
                        <?= $escaper->escapeHtml($faq->getQuestion()) ?>
                    </h4>
                </div>
                <p class="faq-answer" data-role="content"><?= $escaper->escapeHtml($faq->getAnswer()) ?></p>
            </div>
        <?php endforeach; ?>
    </div>

    <script defer>
        require([
            'jquery',
            'accordion'
        ], function($) {
            $(".faq-container").accordion({
                multipleCollapsible: true,
                active: "",
                openedState: "active",
                collapsible: true
            });
        });
    </script>
<?php endif; ?>
