<?php
/** @var \Magebit\Faq\Block\Widget\Faq $block */
/** @var \Magento\Framework\Escaper $escaper */
$activeFaqs = $block->getFaqsByStatus((int)$block->getData('status'));
?>
<?php if(isset($activeFaqs[0])): ?>
    <div class="faq-container">
        <h3 class="faq-title"><?= $escaper->escapeHtml($block->getTitle()) ?></h3>
        <?php foreach ($activeFaqs as $faq): ?>
            <div class="faq-item">
                <div class="faq-question-container">
                    <h4 class="faq-question">
                        <?= $escaper->escapeHtml($faq->getQuestion()) ?>
                    </h4>
                </div>
                <p class="faq-answer"><?= $escaper->escapeHtml($faq->getAnswer()) ?></p>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="faq-container">
        <h3 class="faq-title">FAQ Widget Goes Here</h3>
        <div class="faq-item">
            <div class="faq-question-container">
                <h4 class="faq-question">Is this how a question would look like?</h4>
            </div>
            <p class="faq-answer">
                Yes, right above is an example of how a question would look like. This is an example of an answer.
                This text is shown because there are no FAQs with this widget's "Status of questions" option value.
            </p>
        </div>
    </div>
<?php endif; ?>
